### ISSUE TITLE
Страницы ВСЕ + Модалки ВСЕ (пк+тел) - заменить картинки на СВГ

### ISSUE THREAD

**Issue by winsert1** [winsert1/DurakIssues#14]
![image](https://user-images.githubusercontent.com/96631693/182756999-5bb1bfc2-5329-473b-94ce-2c9caa2fc130.png)

![image](https://user-images.githubusercontent.com/96631693/182757036-9283df87-e80e-400f-9967-13105fac58a8.png)

![image](https://user-images.githubusercontent.com/96631693/182757252-794d0c69-3e94-48d4-9828-a34fe904816d.png)

Настройки для 5и брейкпоинтов: размеры, расположение (на рулетке), Stroke.
![image](https://user-images.githubusercontent.com/96631693/182757412-30f3d656-5f8b-481c-abac-7aa2d127a202.png)

**Comment by winsert1** [comment]
и ещё это (Главная: под рулеткой (пк), снизу страницы (тел))

![image](https://user-images.githubusercontent.com/96631693/183229240-3deede61-6c0d-4fbb-a617-8f08d3282f2f.png)

**Comment by winsert1** [comment]
### Заменить на СВГ

![image](https://user-images.githubusercontent.com/96631693/184314283-b1446035-eabc-4a0b-8d3a-4b8732c97453.png)

![image](https://user-images.githubusercontent.com/96631693/184314322-0865ca76-7439-44d4-bb55-03e3cf4546ca.png)

### Изменить размер

![image](https://user-images.githubusercontent.com/96631693/184314315-8252ca23-60c1-4172-b53e-e0b7312eb0a9.png)

(немного отошёл и всё-таки получилось после 11, но в других были вопросы, время после 11:00 впустую не потрачено)

**Comment by winsert1** [comment]
Это нужно заменять в соответствии с 4я брейкпоинтами (счас не тот размер)

![image](https://user-images.githubusercontent.com/96631693/184402005-11ecc4cd-3285-4f43-be07-deb7a8aa14c0.png)

Тут по прежнему
![image](https://user-images.githubusercontent.com/96631693/184402208-58fb5622-e92b-42f6-af39-3e04ba522893.png)

**Comment by sharaputo** [comment]
С аватаром это нужно кэш почистить, я сбросил, всё отобразилось

**Comment by winsert1** [comment]
У меня работает только на андроиде. На айфоне, кстати, надо бы пофиксить кнопку(за доп. плату), там вообще не меняется аватарка.

![image](https://user-images.githubusercontent.com/96631693/184415119-9d43ad9a-6c1f-4775-8809-f66878e4d3f6.png)

**Comment by sharaputo** [comment]
Пути аватарки пофиксил, там через js менялось, поэтому не отражалось

**Comment by sharaputo** [comment]
на ios пофиксил смену аватара, странный был баг
