### ISSUE TITLE
Чат(тел) - изменить алгоритм работы

### ISSUE THREAD

**Issue by winsert1** [winsert1/DurakIssues#3]
### Изначальная идея(для понимания кода, если будет нужда разбираться):

**Чат при открытии:**

![image](https://user-images.githubusercontent.com/96631693/182296265-b9dcb86d-f3d6-427c-ac2f-19e3d7d0c91d.png)

**Чат при нажатии на область инпута (чат изменяется в длине и смещается вверх):**

![image](https://user-images.githubusercontent.com/96631693/182296363-fb4f1461-c47b-469b-971d-67e8eee39cf8.png)

### Текущая идея:

**Чат при открытии:**

![image](https://user-images.githubusercontent.com/96631693/182296911-b2e7ae77-0622-4b53-8744-7cc956ace748.png)

**Чат при нажатии на область инпута (чат уменьшается):**
Самое нижнее смс в чате у нас - последнее смс чата (то есть, чат не отматывается вверх). Уменьшение/увеличение просьба делать плавным.

![image](https://user-images.githubusercontent.com/96631693/182297092-04a69a21-c325-4039-a635-f1f5a088f79f.png)

**Comment by winsert1** [comment]
**Андроид и айфон**
При отмотке в самый вверх нас отбрасывает вниз - убрать.

**Андроид(хром)**
Возможно убрать резкое подпрыгивание при открытии и закрытии клавиатуры (сделать более плавным, либо вообще убрать мигание верхней части чата)? (в прошлой верстке была такая же штука, из-за чего я решил сделать алгоитм более простым)

**Comment by sharaputo** [comment]
"При отмотке в самый вверх нас отбрасывает вниз - убрать(в старой верстке это тоже убирали)." – пофиксил
"Возможно убрать резкое подпрыгивание при открытии и закрытии клавиатуры (сделать более плавным, либо вообще убрать мигание верхней части чата)? (в прошлой верстке была такая же штука, из-за чего я решил сделать алгоитм более простым)" – это поведение нельзя изменить, внутрянка браузера

**Comment by winsert1** [comment]
""Возможно убрать резкое подпрыгивание при открытии и закрытии клавиатуры (сделать более плавным, либо вообще убрать мигание верхней части чата)? (в прошлой верстке была такая же штука, из-за чего я решил сделать алгоитм более простым)" – это поведение нельзя изменить, внутрянка браузера" - увидел плавность, но на айфоне в сафари: чат при отправке сообщения уменьшается с, отмотанной вниз, страницей (в хроме страница не отматывается) + мы должны видеть самый низ чата (не центр). 

![Uploading image.png…]()
